//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью wsdl, версия=4.6.1055.0.
// 
namespace Lab7.ServiceModel {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProductSeviceSoap", Namespace="http://lab7_my.org/")]
    public partial class ProductSevice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOrderOperationCompleted;
        
        /// <remarks/>
        public ProductSevice() {
            this.Url = "http://localhost:62430/ProductSevice.asmx";
        }
        
        /// <remarks/>
        public event ProductsCompletedEventHandler ProductsCompleted;
        
        /// <remarks/>
        public event ProductCompletedEventHandler ProductCompleted;
        
        /// <remarks/>
        public event DeleteProductCompletedEventHandler DeleteProductCompleted;
        
        /// <remarks/>
        public event UpdateProductCompletedEventHandler UpdateProductCompleted;
        
        /// <remarks/>
        public event AddProductCompletedEventHandler AddProductCompleted;
        
        /// <remarks/>
        public event CustomersCompletedEventHandler CustomersCompleted;
        
        /// <remarks/>
        public event CustomerCompletedEventHandler CustomerCompleted;
        
        /// <remarks/>
        public event DeleteCustomerCompletedEventHandler DeleteCustomerCompleted;
        
        /// <remarks/>
        public event UpdateCustomerCompletedEventHandler UpdateCustomerCompleted;
        
        /// <remarks/>
        public event AddCustomerCompletedEventHandler AddCustomerCompleted;
        
        /// <remarks/>
        public event OrdersCompletedEventHandler OrdersCompleted;
        
        /// <remarks/>
        public event OrderCompletedEventHandler OrderCompleted;
        
        /// <remarks/>
        public event DeleteOrderCompletedEventHandler DeleteOrderCompleted;
        
        /// <remarks/>
        public event UpdateOrderCompletedEventHandler UpdateOrderCompleted;
        
        /// <remarks/>
        public event AddOrderCompletedEventHandler AddOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/Products", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductModel[] Products() {
            object[] results = this.Invoke("Products", new object[0]);
            return ((ProductModel[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginProducts(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Products", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public ProductModel[] EndProducts(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProductModel[])(results[0]));
        }
        
        /// <remarks/>
        public void ProductsAsync() {
            this.ProductsAsync(null);
        }
        
        /// <remarks/>
        public void ProductsAsync(object userState) {
            if ((this.ProductsOperationCompleted == null)) {
                this.ProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductsOperationCompleted);
            }
            this.InvokeAsync("Products", new object[0], this.ProductsOperationCompleted, userState);
        }
        
        private void OnProductsOperationCompleted(object arg) {
            if ((this.ProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductsCompleted(this, new ProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/Product", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductModel Product(int id) {
            object[] results = this.Invoke("Product", new object[] {
                        id});
            return ((ProductModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginProduct(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Product", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProductModel EndProduct(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProductModel)(results[0]));
        }
        
        /// <remarks/>
        public void ProductAsync(int id) {
            this.ProductAsync(id, null);
        }
        
        /// <remarks/>
        public void ProductAsync(int id, object userState) {
            if ((this.ProductOperationCompleted == null)) {
                this.ProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductOperationCompleted);
            }
            this.InvokeAsync("Product", new object[] {
                        id}, this.ProductOperationCompleted, userState);
        }
        
        private void OnProductOperationCompleted(object arg) {
            if ((this.ProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductCompleted(this, new ProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/DeleteProduct", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteProduct(int id) {
            this.Invoke("DeleteProduct", new object[] {
                        id});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteProduct(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteProduct", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndDeleteProduct(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void DeleteProductAsync(int id) {
            this.DeleteProductAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteProductAsync(int id, object userState) {
            if ((this.DeleteProductOperationCompleted == null)) {
                this.DeleteProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProductOperationCompleted);
            }
            this.InvokeAsync("DeleteProduct", new object[] {
                        id}, this.DeleteProductOperationCompleted, userState);
        }
        
        private void OnDeleteProductOperationCompleted(object arg) {
            if ((this.DeleteProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProductCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/UpdateProduct", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateProduct(int id, ProductModel model) {
            this.Invoke("UpdateProduct", new object[] {
                        id,
                        model});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateProduct(int id, ProductModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateProduct", new object[] {
                        id,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateProduct(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void UpdateProductAsync(int id, ProductModel model) {
            this.UpdateProductAsync(id, model, null);
        }
        
        /// <remarks/>
        public void UpdateProductAsync(int id, ProductModel model, object userState) {
            if ((this.UpdateProductOperationCompleted == null)) {
                this.UpdateProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProductOperationCompleted);
            }
            this.InvokeAsync("UpdateProduct", new object[] {
                        id,
                        model}, this.UpdateProductOperationCompleted, userState);
        }
        
        private void OnUpdateProductOperationCompleted(object arg) {
            if ((this.UpdateProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProductCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/AddProduct", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddProduct(ProductModel model) {
            this.Invoke("AddProduct", new object[] {
                        model});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddProduct(ProductModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddProduct", new object[] {
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAddProduct(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void AddProductAsync(ProductModel model) {
            this.AddProductAsync(model, null);
        }
        
        /// <remarks/>
        public void AddProductAsync(ProductModel model, object userState) {
            if ((this.AddProductOperationCompleted == null)) {
                this.AddProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddProductOperationCompleted);
            }
            this.InvokeAsync("AddProduct", new object[] {
                        model}, this.AddProductOperationCompleted, userState);
        }
        
        private void OnAddProductOperationCompleted(object arg) {
            if ((this.AddProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddProductCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/Customers", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerModel[] Customers() {
            object[] results = this.Invoke("Customers", new object[0]);
            return ((CustomerModel[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCustomers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Customers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public CustomerModel[] EndCustomers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerModel[])(results[0]));
        }
        
        /// <remarks/>
        public void CustomersAsync() {
            this.CustomersAsync(null);
        }
        
        /// <remarks/>
        public void CustomersAsync(object userState) {
            if ((this.CustomersOperationCompleted == null)) {
                this.CustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomersOperationCompleted);
            }
            this.InvokeAsync("Customers", new object[0], this.CustomersOperationCompleted, userState);
        }
        
        private void OnCustomersOperationCompleted(object arg) {
            if ((this.CustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomersCompleted(this, new CustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/Customer", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerModel Customer(int id) {
            object[] results = this.Invoke("Customer", new object[] {
                        id});
            return ((CustomerModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCustomer(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Customer", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public CustomerModel EndCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerModel)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerAsync(int id) {
            this.CustomerAsync(id, null);
        }
        
        /// <remarks/>
        public void CustomerAsync(int id, object userState) {
            if ((this.CustomerOperationCompleted == null)) {
                this.CustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerOperationCompleted);
            }
            this.InvokeAsync("Customer", new object[] {
                        id}, this.CustomerOperationCompleted, userState);
        }
        
        private void OnCustomerOperationCompleted(object arg) {
            if ((this.CustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerCompleted(this, new CustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/DeleteCustomer", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteCustomer(int id) {
            this.Invoke("DeleteCustomer", new object[] {
                        id});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteCustomer(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteCustomer", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndDeleteCustomer(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void DeleteCustomerAsync(int id) {
            this.DeleteCustomerAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteCustomerAsync(int id, object userState) {
            if ((this.DeleteCustomerOperationCompleted == null)) {
                this.DeleteCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCustomerOperationCompleted);
            }
            this.InvokeAsync("DeleteCustomer", new object[] {
                        id}, this.DeleteCustomerOperationCompleted, userState);
        }
        
        private void OnDeleteCustomerOperationCompleted(object arg) {
            if ((this.DeleteCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCustomerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/UpdateCustomer", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateCustomer(int id, CustomerModel model) {
            this.Invoke("UpdateCustomer", new object[] {
                        id,
                        model});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateCustomer(int id, CustomerModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateCustomer", new object[] {
                        id,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateCustomer(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void UpdateCustomerAsync(int id, CustomerModel model) {
            this.UpdateCustomerAsync(id, model, null);
        }
        
        /// <remarks/>
        public void UpdateCustomerAsync(int id, CustomerModel model, object userState) {
            if ((this.UpdateCustomerOperationCompleted == null)) {
                this.UpdateCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCustomerOperationCompleted);
            }
            this.InvokeAsync("UpdateCustomer", new object[] {
                        id,
                        model}, this.UpdateCustomerOperationCompleted, userState);
        }
        
        private void OnUpdateCustomerOperationCompleted(object arg) {
            if ((this.UpdateCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCustomerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/AddCustomer", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddCustomer(CustomerModel model) {
            this.Invoke("AddCustomer", new object[] {
                        model});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddCustomer(CustomerModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddCustomer", new object[] {
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAddCustomer(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void AddCustomerAsync(CustomerModel model) {
            this.AddCustomerAsync(model, null);
        }
        
        /// <remarks/>
        public void AddCustomerAsync(CustomerModel model, object userState) {
            if ((this.AddCustomerOperationCompleted == null)) {
                this.AddCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCustomerOperationCompleted);
            }
            this.InvokeAsync("AddCustomer", new object[] {
                        model}, this.AddCustomerOperationCompleted, userState);
        }
        
        private void OnAddCustomerOperationCompleted(object arg) {
            if ((this.AddCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCustomerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/Orders", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderModel[] Orders() {
            object[] results = this.Invoke("Orders", new object[0]);
            return ((OrderModel[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOrders(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Orders", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public OrderModel[] EndOrders(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrderModel[])(results[0]));
        }
        
        /// <remarks/>
        public void OrdersAsync() {
            this.OrdersAsync(null);
        }
        
        /// <remarks/>
        public void OrdersAsync(object userState) {
            if ((this.OrdersOperationCompleted == null)) {
                this.OrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrdersOperationCompleted);
            }
            this.InvokeAsync("Orders", new object[0], this.OrdersOperationCompleted, userState);
        }
        
        private void OnOrdersOperationCompleted(object arg) {
            if ((this.OrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrdersCompleted(this, new OrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/Order", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderModel Order(int id) {
            object[] results = this.Invoke("Order", new object[] {
                        id});
            return ((OrderModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOrder(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Order", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public OrderModel EndOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrderModel)(results[0]));
        }
        
        /// <remarks/>
        public void OrderAsync(int id) {
            this.OrderAsync(id, null);
        }
        
        /// <remarks/>
        public void OrderAsync(int id, object userState) {
            if ((this.OrderOperationCompleted == null)) {
                this.OrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderOperationCompleted);
            }
            this.InvokeAsync("Order", new object[] {
                        id}, this.OrderOperationCompleted, userState);
        }
        
        private void OnOrderOperationCompleted(object arg) {
            if ((this.OrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderCompleted(this, new OrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/DeleteOrder", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteOrder(int id) {
            this.Invoke("DeleteOrder", new object[] {
                        id});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteOrder(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteOrder", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndDeleteOrder(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void DeleteOrderAsync(int id) {
            this.DeleteOrderAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteOrderAsync(int id, object userState) {
            if ((this.DeleteOrderOperationCompleted == null)) {
                this.DeleteOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOrderOperationCompleted);
            }
            this.InvokeAsync("DeleteOrder", new object[] {
                        id}, this.DeleteOrderOperationCompleted, userState);
        }
        
        private void OnDeleteOrderOperationCompleted(object arg) {
            if ((this.DeleteOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/UpdateOrder", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateOrder(int id, OrderModel model) {
            this.Invoke("UpdateOrder", new object[] {
                        id,
                        model});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateOrder(int id, OrderModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateOrder", new object[] {
                        id,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateOrder(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void UpdateOrderAsync(int id, OrderModel model) {
            this.UpdateOrderAsync(id, model, null);
        }
        
        /// <remarks/>
        public void UpdateOrderAsync(int id, OrderModel model, object userState) {
            if ((this.UpdateOrderOperationCompleted == null)) {
                this.UpdateOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderOperationCompleted);
            }
            this.InvokeAsync("UpdateOrder", new object[] {
                        id,
                        model}, this.UpdateOrderOperationCompleted, userState);
        }
        
        private void OnUpdateOrderOperationCompleted(object arg) {
            if ((this.UpdateOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lab7_my.org/AddOrder", RequestNamespace="http://lab7_my.org/", ResponseNamespace="http://lab7_my.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddOrder(OrderModel model) {
            this.Invoke("AddOrder", new object[] {
                        model});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddOrder(OrderModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddOrder", new object[] {
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAddOrder(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void AddOrderAsync(OrderModel model) {
            this.AddOrderAsync(model, null);
        }
        
        /// <remarks/>
        public void AddOrderAsync(OrderModel model, object userState) {
            if ((this.AddOrderOperationCompleted == null)) {
                this.AddOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrderOperationCompleted);
            }
            this.InvokeAsync("AddOrder", new object[] {
                        model}, this.AddOrderOperationCompleted, userState);
        }
        
        private void OnAddOrderOperationCompleted(object arg) {
            if ((this.AddOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lab7_my.org/")]
    public partial class ProductModel {
        
        private int idField;
        
        private double priceField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lab7_my.org/")]
    public partial class OrderModel {
        
        private int customerIdField;
        
        private int productIdField;
        
        private int countField;
        
        /// <remarks/>
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lab7_my.org/")]
    public partial class CustomerModel {
        
        private int idField;
        
        private string nameField;
        
        private int ageField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ProductsCompletedEventHandler(object sender, ProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ProductCompletedEventHandler(object sender, ProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void DeleteProductCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void UpdateProductCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void AddProductCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void CustomersCompletedEventHandler(object sender, CustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void CustomerCompletedEventHandler(object sender, CustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void DeleteCustomerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void UpdateCustomerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void AddCustomerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void OrdersCompletedEventHandler(object sender, OrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void OrderCompletedEventHandler(object sender, OrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void DeleteOrderCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void UpdateOrderCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void AddOrderCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}
